import { MatchOpportunity, User, Message, Team, TeamInvite } from './types'

const _mockCreated = new Date('2024-01-01')

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'carlos@example.com',
    name: 'Carlos Muñoz',
    age: 28,
    gender: 'male',
    position: 'delantero',
    level: 'avanzado',
    city: 'Rancagua',
    availability: ['sabado', 'domingo'],
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
    bio: 'Jugador apasionado, buscando equipos competitivos',
    createdAt: _mockCreated,
  },
  {
    id: '2',
    email: 'diego@example.com',
    name: 'Diego Soto',
    age: 25,
    gender: 'male',
    position: 'mediocampista',
    level: 'intermedio',
    city: 'Rancagua',
    availability: ['viernes', 'sabado'],
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face',
    bio: 'Mediocampista creativo con buen pase',
    createdAt: _mockCreated,
  },
  {
    id: '3',
    email: 'andres@example.com',
    name: 'Andrés Vega',
    age: 32,
    gender: 'male',
    position: 'defensa',
    level: 'competitivo',
    city: 'Rancagua',
    availability: ['sabado', 'domingo'],
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face',
    bio: 'Defensa central con experiencia',
    createdAt: _mockCreated,
  },
  {
    id: '4',
    email: 'matias@example.com',
    name: 'Matías Reyes',
    age: 23,
    gender: 'male',
    position: 'portero',
    level: 'intermedio',
    city: 'Rancagua',
    availability: ['domingo'],
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face',
    bio: 'Portero con buenos reflejos',
    createdAt: _mockCreated,
  },
  {
    id: '5',
    email: 'felipe@example.com',
    name: 'Felipe Torres',
    age: 27,
    gender: 'male',
    position: 'delantero',
    level: 'avanzado',
    city: 'Rancagua',
    availability: ['viernes', 'sabado', 'domingo'],
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face',
    bio: 'Goleador nato, siempre listo para jugar',
    createdAt: _mockCreated,
  },
  {
    id: '6',
    email: 'maria@example.com',
    name: 'María González',
    age: 24,
    gender: 'female',
    position: 'mediocampista',
    level: 'avanzado',
    city: 'Rancagua',
    availability: ['sabado', 'domingo'],
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face',
    bio: 'Mediocampista con visión de juego',
    createdAt: _mockCreated,
  },
  {
    id: '7',
    email: 'camila@example.com',
    name: 'Camila Rojas',
    age: 22,
    gender: 'female',
    position: 'delantero',
    level: 'intermedio',
    city: 'Rancagua',
    availability: ['viernes', 'sabado'],
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face',
    bio: 'Delantera rápida con buen regate',
    createdAt: _mockCreated,
  },
]

export const mockMatches: MatchOpportunity[] = [
  {
    id: '1',
    type: 'rival',
    title: 'Los Cracks buscan rival',
    description: 'Equipo nivel avanzado busca partido amistoso para este fin de semana',
    location: 'Rancagua',
    venue: 'Cancha El Teniente',
    dateTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    level: 'avanzado',
    creatorId: '1',
    creatorName: 'Carlos Muñoz',
    creatorPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
    teamName: 'Los Cracks FC',
    gender: 'male',
    status: 'pending',
    createdAt: new Date(),
  },
  {
    id: '2',
    type: 'players',
    title: 'Faltan 2 jugadores',
    description: 'Necesitamos mediocampista y delantero para completar equipo',
    location: 'Rancagua',
    venue: 'Complejo Deportivo Norte',
    dateTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    level: 'intermedio',
    creatorId: '2',
    creatorName: 'Diego Soto',
    creatorPhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face',
    teamName: 'Real Rancagua',
    playersNeeded: 2,
    playersJoined: 4,
    gender: 'male',
    status: 'pending',
    createdAt: new Date(),
  },
  {
    id: '3',
    type: 'open',
    title: 'Partido abierto domingo',
    description: 'Revuelta para todos los niveles, vengan a pasarla bien',
    location: 'Rancagua',
    venue: 'Cancha Municipal Sur',
    dateTime: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    level: 'intermedio',
    creatorId: '3',
    creatorName: 'Andrés Vega',
    creatorPhoto: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face',
    playersNeeded: 12,
    playersJoined: 7,
    gender: 'male',
    status: 'pending',
    createdAt: new Date(),
  },
  {
    id: '4',
    type: 'rival',
    title: 'Deportivo Sur vs ???',
    description: 'Equipo competitivo busca rival de nivel similar',
    location: 'Rancagua',
    venue: 'Estadio Municipal',
    dateTime: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    level: 'competitivo',
    creatorId: '5',
    creatorName: 'Felipe Torres',
    creatorPhoto: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face',
    teamName: 'Deportivo Sur',
    gender: 'male',
    status: 'pending',
    createdAt: new Date(),
  },
  {
    id: '5',
    type: 'players',
    title: 'Buscamos portera',
    description: 'Equipo femenino necesita portera para torneo',
    location: 'Rancagua',
    venue: 'Cancha Las Acacias',
    dateTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    level: 'avanzado',
    creatorId: '6',
    creatorName: 'María González',
    creatorPhoto: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face',
    teamName: 'Las Leonas',
    playersNeeded: 1,
    playersJoined: 5,
    gender: 'female',
    status: 'pending',
    createdAt: new Date(),
  },
  {
    id: '6',
    type: 'open',
    title: 'Partido mixto casual',
    description: 'Partido relajado, todos bienvenidos',
    location: 'Rancagua',
    venue: 'Parque O\'Higgins',
    dateTime: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    level: 'principiante',
    creatorId: '7',
    creatorName: 'Camila Rojas',
    creatorPhoto: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face',
    playersNeeded: 10,
    playersJoined: 4,
    gender: 'female',
    status: 'pending',
    createdAt: new Date(),
  },
]

export const mockTeams: Team[] = [
  {
    id: 'team-1',
    name: 'Los Cracks FC',
    logo: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=200&h=200&fit=crop',
    level: 'avanzado',
    captainId: '1',
    members: [
      { id: '1', name: 'Carlos Muñoz', position: 'delantero', photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face', status: 'confirmed' },
      { id: '2', name: 'Diego Soto', position: 'mediocampista', photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face', status: 'confirmed' },
      { id: '3', name: 'Andrés Vega', position: 'defensa', photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face', status: 'confirmed' },
      { id: '4', name: 'Matías Reyes', position: 'portero', photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face', status: 'pending' },
    ],
    city: 'Rancagua',
    gender: 'male',
    description: 'Equipo competitivo buscando nuevos desafíos',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'team-2',
    name: 'Real Rancagua',
    logo: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=200&h=200&fit=crop',
    level: 'intermedio',
    captainId: '2',
    members: [
      { id: '2', name: 'Diego Soto', position: 'mediocampista', photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face', status: 'confirmed' },
      { id: '5', name: 'Felipe Torres', position: 'delantero', photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face', status: 'confirmed' },
    ],
    city: 'Rancagua',
    gender: 'male',
    description: 'Equipo en formación, buscamos jugadores comprometidos',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'team-3',
    name: 'Las Leonas',
    logo: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=200&h=200&fit=crop',
    level: 'avanzado',
    captainId: '6',
    members: [
      { id: '6', name: 'María González', position: 'mediocampista', photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face', status: 'confirmed' },
      { id: '7', name: 'Camila Rojas', position: 'delantero', photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face', status: 'confirmed' },
    ],
    city: 'Rancagua',
    gender: 'female',
    description: 'Equipo femenino con garra y pasión',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
  },
]

export const mockTeamInvites: TeamInvite[] = [
  {
    id: 'invite-1',
    teamId: 'team-1',
    teamName: 'Los Cracks FC',
    inviterId: '1',
    inviterName: 'Carlos Muñoz',
    inviteeId: '5',
    status: 'pending',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
]

export const mockMessages: Message[] = [
  {
    id: '1',
    matchId: '1',
    senderId: '1',
    content: '¡Hola! ¿Están listos para el partido?',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: '2',
    matchId: '1',
    senderId: '2',
    content: 'Sí, llegamos a las 10am',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: '3',
    matchId: '1',
    senderId: '1',
    content: 'Perfecto, nos vemos ahí',
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
  },
]
